---
language:     ruby
bundler_args: --without metrics
cache:        bundler
rvm:
  - '1.9.3'
  - '2.0'
  - '2.1'
  - '2.2'
  - ruby-head
  - rbx-2 --1.9
  - rbx-2 --2.1
  - jruby-1.7-19mode
  - jruby-9.0.0.0.pre2
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
